server:
  port: 8081

spring:
  datasource:
    username: root
    password: 125800
    url: jdbc:mysql://localhost:3306/masteryi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.wuyan.masteryi.admin.entity
  configuration:
    map-underscore-to-camel-case: true