server:
  port: 8081

spring:
  redis:
    host: 49.232.159.181
    port: 6379
    password:
    timeout: 3000
    max-idle: 200
    max-active: 2000
    max-wait: 1000

  datasource:
    username: root
    password: 125800
    url: jdbc:mysql://localhost:3306/masteryi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.wuyan.masteryi.admin.entity
  configuration:
    map-underscore-to-camel-case: true