server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/masteryi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 49.232.159.181
    port: 6380
    password: test123
    timeout: 3000
    max-idle: 200
    max-active: 2000
    max-wait: 1000

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.wuyan.masteryi.mall.entity
  configuration:
    map-underscore-to-camel-case: true


